# Generated by Django 4.1.5 on 2023-01-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='medidor',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
