# Generated by Django 4.1.5 on 2023-01-12 04:40

import clientes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_medidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoresBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cifra_base', models.DecimalField(decimal_places=2, max_digits=30)),
                ('valor_adicional', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('base', models.IntegerField()),
                ('porcentaje_mora', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cifras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=10)),
                ('anio', models.CharField(max_length=4)),
                ('cifra', models.IntegerField()),
                ('id_valores', models.CharField(max_length=10, verbose_name=clientes.models.ValoresBase)),
                ('estado', models.CharField(default='n', max_length=1)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
