# Generated by Django 4.1.5 on 2023-01-12 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_remove_cifras_id_valores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('fechacifra', models.CharField(max_length=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=30)),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
